# This is a basic workflow that is manually triggered

name: venus

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    name: venus ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          go mod download
          cd cmd/venusd
          go build .
          cd ..
          cd venuscli
          go build .


 	  - uses: actions/upload-artifact@v2
        with:
          name: venuscli ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/venuscli/venuscli

      - uses: actions/upload-artifact@v2
        with:
          name: venusd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/venusd/venusd

